version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "narazaki-shoten-stack"
resolve_s3 = true
s3_prefix = "narazaki-shoten-stack"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
